### ISSUE TITLE
Repositioning of datepicker pop up

### ISSUE THREAD

**Issue by arunnbabu81** [NicolasPetton/Projectify#14] opened 2021-01-05 22:01 UTC
When i installed projectify 0.8 in Krystal based TW (which has horizontally arranged tiddler), the date picker pop up is overlapping the right margin of the projects tiddler and is getting partly hidden. I have to scroll to the right to fully reveal the date picker pop up. I have attached a demo in this attached file. This behavior was not seen in any other story views. The previous version of projectify was working fine even in TW using Krystal plug in.

[Krystal 0.3.2 + projectify 0.8 = for  test.zip](https://github.com/NicolasPetton/Projectify/files/5772788/Krystal.0.3.2.%2B.projectify.0.8.for.test.zip)

**Comment by NicolasPetton** [comment] 2021-01-06 08:08
Thanks for reporting the issue @arunnbabu81. The bug is fixed in master, commit df838bc.

**Closed by NicolasPetton** 2021-01-06 08:08 UTC
Labels: bug

**Comment by arunnbabu81** [comment] 2021-01-08 13:22
i was not able to change the month and year using the month and year selector in the date picker tool. I was trying it in my windows 10  laptop in chrome and edge browser. On clicking the month and year selector of the date picker tool, a vertical list of months and years will pop up which will disappear suddenly without allowing to select  the month or the year.

**Comment by NicolasPetton** [comment] 2021-01-08 15:25
@arunnbabu81 Thanks, that's definitely a bug.

As a workaround, have you tried a long click?

**Comment by arunnbabu81** [comment] 2021-01-08 16:37
> @arunnbabu81 Thanks, that's definitely a bug.
> 
> As a workaround, have you tried a long click?

Ya...on long press the pop up list stays instead of disappearing and then I could use “up and down arrow keys” to select the month or year.

**Comment by NicolasPetton** [comment] 2021-01-08 17:23
It's fixed in master (commit 26e8b2d).

**Comment by arunnbabu81** [comment] 2021-01-08 20:42
Both the bugs are fixed in the 0.9 version. Thanks for the update

**Comment by NicolasPetton** [comment] 2021-01-08 21:25
You're welcome, thanks for reporting them :)

**Comment by arunnbabu81** [comment] 2021-01-11 11:43
The date picker in mobile ( both android and iOS) is showing the the short form of a day with its expansion in bracket 

like this Mon (Monday) Tue (Tuesday) and so on. This makes the calendar to look little stretched out in mobile.

Is it an expected behavior

**Comment by NicolasPetton** [comment] 2021-01-11 12:05
Can you upload a screenshot?

**Comment by arunnbabu81** [comment] 2021-01-11 12:46
![Projectify](https://user-images.githubusercontent.com/67494083/104184175-0d6c4300-5439-11eb-8115-4271c0f52d26.png)

**Comment by NicolasPetton** [comment] 2021-01-11 14:08
hmm, I can't reproduce it on Andoid, would you mind posting an html wiki here so I can see what's wrong?

**Comment by arunnbabu81** [comment] 2021-01-11 16:54
I am sorry. This must be due to conflicts with one of the plug ins installed in my wiki. I tried to install projectify in an empty wiki with Krystal plug in. In that wiki, the calendar was working fine with iOS (I didn’t checked in android). I will check later what is causing the conflict when I get time. Sorry for the trouble.

**Comment by NicolasPetton** [comment] 2021-01-11 17:13
@arunnbabu81 no problem. If you find out which plugin is causing this issue, I can try to find a workaround.

**Comment by arunnbabu81** [comment] 2021-01-11 17:36
I will inform here once I find it. But it may take a few days.

**Comment by arunnbabu81** [comment] 2021-01-12 17:17
I found conflicts with two plug ins when used in **mobile phone**.
 1. Kookma Refnote  plug-in is causing stretching of calendar in datepicker.
 2. Wikilabs Edit tabs plug-in is causing vertical alignment of tabs in dashboard instead of horizontal. When we select one tab, the tabs to the right of it goes into vertical orientation.

I have attached the separate files  for demo. 
[demo.zip](https://github.com/NicolasPetton/Projectify/files/5803717/demo.zip)

**Comment by NicolasPetton** [comment] 2021-01-12 17:36
@arunnbabu81 thanks!

@kookma would you accept a PR fixing the issue in Refnote?

**Comment by NicolasPetton** [comment] 2021-01-12 17:36
> Wikilabs Edit tabs plug-in is causing vertical alignment of tabs in dashboard instead of horizontal. When we select one tab, the tabs to the right of it goes into vertical orientation.

That's something I can fix in Projectify.

**Comment by kookma** [comment] 2021-01-13 03:26
> @arunnbabu81 thanks!
> 
> @kookma would you accept a PR fixing the issue in Refnote?

@NicolasPetton - Sure I will look at Refnote. By the way a rewrite of Refnote is planning for mid Feb.

**Comment by NicolasPetton** [comment] 2021-01-13 10:25
@arunnbabu81 the bug with the WikiLabs Edit tab plugin is fixed in 40aaf677c16b202f546dd71819e7e92d540478cc.
