### ISSUE TITLE
Items scheduled for today show yesterday's date

### ISSUE THREAD

**Issue by dixonge** [NicolasPetton/Projectify#12] opened 2020-12-24 12:43 UTC
Every item I schedule (using the date picker calendar) is assigned to the previous day. 

When I edit an entry, the 'due:' field shows today's date like this ```20201224000000000```

But the text associated with it says it is overdue, because it is assigned to the day *before* the date shown above. (i.e., Dec. 23)

This happens on every item I have tried to schedule. It is the same in my browser (Firefox) or TiddlyDesktop.

TW v. 5.1.22
MacOS 11.0.1 (Big Sur)

**Comment by NicolasPetton** [comment] 2020-12-24 13:29
I cannot reproduce it locally. Could you upload a minimal wiki here so I can reproduce the issue?

**Comment by NicolasPetton** [comment] 2020-12-24 13:31
@dixonge could it be a timezone issue?

**Comment by dixonge** [comment] 2020-12-24 13:40
I thought about that. I am running it locally on my laptop. My system time matches actual time in this time zone, and I'm not sure where else Projectify would look for any other time, so ... ?

Using kixam's datepicker v0.5.2 - I guess your plugin gets the date from that one?

**Comment by dixonge** [comment] 2020-12-24 13:50
FYI, just downloaded a preconfigured version from your demo page - same result.

**Comment by saqimtiaz** [comment] 2020-12-24 15:18
@NicolasPetton I think this is the underlying issue: https://github.com/Jermolene/TiddlyWiki5/issues/2061

**Comment by dixonge** [comment] 2020-12-24 15:26
@saqimtiaz thanks!

In looking at the timestamp coming from datepicker/moments, it has the date but no time. I'm guessing TW interprets this as midnight, which is being set to the day before instead of the day of. If I manually change ```20201224000000000``` to ```20201224100000000``` then the scheduled date shifts to today and all is well.

So fixing the plugin to do that is now the trick...

**Comment by NicolasPetton** [comment] 2020-12-28 23:42
Redoing the date picker is next on my list, I'll see if I can find a fix as well.

@dixonge could you tell me what timezone you're in to help me debug the issue?

**Comment by dixonge** [comment] 2020-12-29 11:01
Central

**Comment by NicolasPetton** [comment] 2021-01-05 20:34
@dixonge I believe the bug should be fixed in master, see commit 903aadc.

**Closed by NicolasPetton** 2021-01-05 20:34 UTC
Labels: bug

**Comment by dixonge** [comment] 2021-01-05 22:59
0.8.0 is working, merci!
